#' @title package loading
#' loading essential libraries
#' put in Rprofile to be executed at startup
globalVariables(c("varnames", "<<-"))
library(shiny)
library(shinydashboard)
library(foreign)
library(readxl)
library(tools)
library(pROC)
library(ggplot2)
library(dplyr)
library(randomForestSRC)
library(pracma)
library(xgboost)
library(mlr3learners)
library(mlr3extralearners)
library(mlr3proba)
library(caret)
library(utils)
