on:
  push:
    branches: [main, packaged-v]
  pull_request:
    branches: [main, packaged-v]
    
name: Check-New-Dataset
    
jobs:
  check-new-dataset-presence:
    runs-on: ubuntu-latest
    name: check uploaded new dataset file 
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: find last modified files in data directory
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            R/datasets/dataset.RDS

      - name: condition to check file last modification success
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "New dataset file has been added..."
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'devtools::load_all(".")
          R CMD INSTALL --no-multiarch --with-keep.source primace
          Rscript -e "primace::preprocessing()"
          echo "Preprocessing finished successfully..."
        
      - name: condition to checl file last modification fail
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "No new dataset file has been added..."
