on:
  push:
    branches: [main, packaged-v]
  pull_request:
    branches: [main, packaged-v]
    
name: Check-New-Dataset
    
jobs:
  check-new-dataset-presence:
    runs-on: ubuntu-latest
    name: Check Uploaded New Dataset File 
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"shiny"'
          
      - name: Install texlive
        run : |
            sudo apt-get install texlive
            sudo apt-get install texlive-fonts-extra
          
      - name: R CMD CHECK
        run : |
            rcmdcheck::rcmdcheck(error_on="warning")
        shell : Rscript {0}
            
      - name: Find Last Modified File in R/dataset directory
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            R/datasets/dataset.RDS

      - name: Check File Last Modification - SUCCESS
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run : |
          devtools::load_all(".")
          devtools::build()
          library(primace)
          primace::preprocessing()
        shell : Rscript {0}
          
      - name: Check File Last Modification - FAILURE
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo -e "\033[1;31mNo new dataset file has been added..."
