on:
  push:
    branches: [main, packaged-v]
  pull_request:
    branches: [main, packaged-v]
    
name: Check-New-Dataset
    
jobs:
  check-new-dataset-presence:
    runs-on: ubuntu-latest
    name: check uploaded new dataset file 
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"shiny"'
          
      - name: install texlive
        run : |
            sudo apt-get install texlive
            sudo apt-get install texlive-fonts-extra
          
      - name: R CMD CHECK inside r
        run : |
            rcmdcheck::rcmdcheck(error_on="warning")
        shell : Rscript {0}
            
      - name: find last modified files in data directory
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            R/datasets/dataset.RDS

      - name: condition to check file last modification success
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run : |
          devtools::load_all(".")
          devtools::build()
          library(primace)
        shell : Rscript {0}
          
      - name: condition to checl file last modification fail
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "No new dataset file has been added..."
