on:
  push:
    branches: [main, packaged-v]
  pull_request:
    branches: [main, packaged-v]
    
name: Check-New-Dataset
    
jobs:
  check-new-dataset-presence:
    runs-on: ubuntu-latest
    name: check uploaded new dataset file 
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: find last modified files in data directory
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            R/data/**

      - name: condition to check file last modification success
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: echo "New dataset file has been added"
        
      - name: condition to checl file last modification fail
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: exit 64

  upload-Dataset:
    runs-on: ubuntu-latest
    needs: check-new-dataset-presence
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
    
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
    
      - uses: r-lib/actions/setup-renv@v2

      - name: Run Preprocessing.R
        run : |
            R/preprocessing.R
        shell : Rscript {0}
        
      - name: success
        run: echo "Done..."
